
################################################################################
#
# This gnuplot file was generated by MadGraph5_aMC@NLO project, a program which 
# automatically generates Feynman diagrams and matrix elements for arbitrary
# high-energy processes in the Standard Model and beyond. It also perform the
# integration and/or generate events for these processes, at LO and NLO accuracy.
#
# For more information, visit madgraph.phys.ucl.ac.be and amcatnlo.web.cern.ch
#
################################################################################
# ./internal/histograms.py events__6_2_-1_1_2_-2_21_21_1_2_3_5_6_4.HwU events__6_2_-1_1_2_-2_21_21_1_2_3_6_5_4.HwU events__6_2_-1_1_2_-2_21_21_1_4_3_5_6_2.HwU events__6_2_-1_1_2_-2_21_21_1_4_3_6_5_2.HwU events__6_2_-1_1_2_-2_21_21_1_5_2_3_6_4.HwU events__6_2_-1_1_2_-2_21_21_1_5_4_3_6_2.HwU events__6_2_-1_1_2_-2_21_21_1_5_6_2_3_4.HwU events__6_2_-1_1_2_-2_21_21_1_5_6_4_3_2.HwU events__6_2_-1_1_2_-2_21_21_1_6_2_3_5_4.HwU events__6_2_-1_1_2_-2_21_21_1_6_4_3_5_2.HwU events__6_2_-1_1_2_-2_21_21_1_6_5_2_3_4.HwU events__6_2_-1_1_2_-2_21_21_1_6_5_4_3_2.HwU --sum --no_stat --out=sum_2qq_6__ --no_open
reset

set lmargin 10
set rmargin 0
set terminal postscript portrait enhanced color "Helvetica" 15
# The pdf terminal offers transparency support, but you will have to adapt things a bit
#set terminal pdf enhanced font "Helvetica 12" lw 1.0 dashed size 29.7cm, 21cm
set key font ",15"
set key samplen "2"
set output "sum_2qq_6__.ps"

# This is the "PODO" color palette of gnuplot v.5, but with the order
# changed: palette of colors selected to be easily distinguishable by
# color-blind individuals with either protanopia or deuteranopia. Bang
# Wong [2011] Nature Methods 8, 441.

set style line   1 lt 1 lc rgb "#009e73" lw 2.0
set style line 101 lt 1 lc rgb "#009e73" lw 2.0 dt (6,3)
set style line  11 lt 2 lc rgb "#009e73" lw 2.0 dt (6,3)
set style line  21 lt 4 lc rgb "#009e73" lw 2.0 dt (3,2)
set style line  31 lt 6 lc rgb "#009e73" lw 2.0 dt (2,1)
set style line  41 lt 8 lc rgb "#009e73" lw 2.0 dt (4,3)

set style line   2 lt 1 lc rgb "#0072b2" lw 2.0
set style line 102 lt 1 lc rgb "#0072b2" lw 2.0 dt (6,3)
set style line  12 lt 2 lc rgb "#0072b2" lw 2.0 dt (6,3)
set style line  22 lt 4 lc rgb "#0072b2" lw 2.0 dt (3,2)
set style line  32 lt 6 lc rgb "#0072b2" lw 2.0 dt (2,1)
set style line  42 lt 8 lc rgb "#0072b2" lw 2.0 dt (4,3)

set style line   3 lt 1 lc rgb "#d55e00" lw 2.0
set style line 103 lt 1 lc rgb "#d55e00" lw 2.0 dt (6,3)
set style line  13 lt 2 lc rgb "#d55e00" lw 2.0 dt (6,3)
set style line  23 lt 4 lc rgb "#d55e00" lw 2.0 dt (3,2)
set style line  33 lt 6 lc rgb "#d55e00" lw 2.0 dt (2,1)
set style line  43 lt 8 lc rgb "#d55e00" lw 2.0 dt (4,3)

set style line   4 lt 1 lc rgb "#f0e442" lw 2.0
set style line 104 lt 1 lc rgb "#f0e442" lw 2.0 dt (6,3)
set style line  14 lt 2 lc rgb "#f0e442" lw 2.0 dt (6,3)
set style line  24 lt 4 lc rgb "#f0e442" lw 2.0 dt (3,2)
set style line  34 lt 6 lc rgb "#f0e442" lw 2.0 dt (2,1)
set style line  44 lt 8 lc rgb "#f0e442" lw 2.0 dt (4,3)

set style line   5 lt 1 lc rgb "#56b4e9" lw 2.0
set style line 105 lt 1 lc rgb "#56b4e9" lw 2.0 dt (6,3)
set style line  15 lt 2 lc rgb "#56b4e9" lw 2.0 dt (6,3)
set style line  25 lt 4 lc rgb "#56b4e9" lw 2.0 dt (3,2)
set style line  35 lt 6 lc rgb "#56b4e9" lw 2.0 dt (2,1)
set style line  45 lt 8 lc rgb "#56b4e9" lw 2.0 dt (4,3)

set style line   6 lt 1 lc rgb "#cc79a7" lw 2.0
set style line 106 lt 1 lc rgb "#cc79a7" lw 2.0 dt (6,3)
set style line  16 lt 2 lc rgb "#cc79a7" lw 2.0 dt (6,3)
set style line  26 lt 4 lc rgb "#cc79a7" lw 2.0 dt (3,2)
set style line  36 lt 6 lc rgb "#cc79a7" lw 2.0 dt (2,1)
set style line  46 lt 8 lc rgb "#cc79a7" lw 2.0 dt (4,3)

set style line   7 lt 1 lc rgb "#e69f00" lw 2.0
set style line 107 lt 1 lc rgb "#e69f00" lw 2.0 dt (6,3)
set style line  17 lt 2 lc rgb "#e69f00" lw 2.0 dt (6,3)
set style line  27 lt 4 lc rgb "#e69f00" lw 2.0 dt (3,2)
set style line  37 lt 6 lc rgb "#e69f00" lw 2.0 dt (2,1)
set style line  47 lt 8 lc rgb "#e69f00" lw 2.0 dt (4,3)

set style line   8 lt 1 lc rgb "black" lw 2.0
set style line 108 lt 1 lc rgb "black" lw 2.0 dt (6,3)
set style line  18 lt 2 lc rgb "black" lw 2.0 dt (6,3)
set style line  28 lt 4 lc rgb "black" lw 2.0 dt (3,2)
set style line  38 lt 6 lc rgb "black" lw 2.0 dt (2,1)
set style line  48 lt 8 lc rgb "black" lw 2.0 dt (4,3)


set style line 999 lt 1 lc rgb "gray" lw 2.0

safe(x,y,a) = (y == 0.0 ? a : x/y)

set style data histeps
set key invert



################################################################################
### Rendering of the plot titled 'rates'
################################################################################

set multiplot
set label "rates" font ",15" at graph 0.04, graph 1.05
set xrange [0.0000e+00:3.0000e+00]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [1.6724e+01:3.3709e+02]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 0 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 0 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'rates ratios'
################################################################################

set multiplot
set label "rates ratios" font ",15" at graph 0.04, graph 1.05
set xrange [0.0000e+00:3.0000e+00]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [1.6724e+01:3.3709e+02]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 1 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 1 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio NLC/LC narrow'
################################################################################

set multiplot
set label "ratio NLC/LC narrow" font ",15" at graph 0.04, graph 1.05
set xrange [7.0000e-01:1.4000e+00]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [2.7637e-11:4.8375e+00]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 2 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 2 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio full/LC narrow'
################################################################################

set multiplot
set label "ratio full/LC narrow" font ",15" at graph 0.04, graph 1.05
set xrange [7.0000e-01:1.4000e+00]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [5.5273e-11:6.9096e+00]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 3 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 3 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio full/NLC narrow'
################################################################################

set multiplot
set label "ratio full/NLC narrow" font ",15" at graph 0.04, graph 1.05
set xrange [9.5000e-01:1.0500e+00]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [2.8745e-08:2.6214e+00]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 4 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 4 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio log10(NLC/LC) narrow'
################################################################################

set multiplot
set label "ratio log10(NLC/LC) narrow" font ",15" at graph 0.04, graph 1.05
set xrange [-5.0000e-01:5.0000e-01]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [2.3327e-10:1.8239e+01]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 5 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 5 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio log10(full/LC) narrow'
################################################################################

set multiplot
set label "ratio log10(full/LC) narrow" font ",15" at graph 0.04, graph 1.05
set xrange [-5.0000e-01:5.0000e-01]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [9.6182e-11:2.6379e+01]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 6 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 6 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio log10(full/NLC) narrow'
################################################################################

set multiplot
set label "ratio log10(full/NLC) narrow" font ",15" at graph 0.04, graph 1.05
set xrange [-5.0000e-02:5.0000e-02]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [1.0561e-08:5.9689e+00]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 7 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 7 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio NLC/LC'
################################################################################

set multiplot
set label "ratio NLC/LC" font ",15" at graph 0.04, graph 1.05
set xrange [-2.5000e+01:2.5000e+01]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [1.4222e-07:2.7288e+02]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 8 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 8 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio full/LC'
################################################################################

set multiplot
set label "ratio full/LC" font ",15" at graph 0.04, graph 1.05
set xrange [-2.5000e+01:2.5000e+01]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [4.1897e-08:3.2193e+02]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 9 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 9 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio full/NLC'
################################################################################

set multiplot
set label "ratio full/NLC" font ",15" at graph 0.04, graph 1.05
set xrange [-2.5000e+01:2.5000e+01]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [3.4486e-08:2.8599e+02]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 10 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 10 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio log10(NLC/LC)'
################################################################################

set multiplot
set label "ratio log10(NLC/LC)" font ",15" at graph 0.04, graph 1.05
set xrange [-2.0000e+00:2.0000e+00]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [3.0212e-09:6.8947e+01]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 11 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 11 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio log10(full/LC)'
################################################################################

set multiplot
set label "ratio log10(full/LC)" font ",15" at graph 0.04, graph 1.05
set xrange [-2.0000e+00:2.0000e+00]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [5.7828e-09:9.6440e+01]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 12 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 12 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio log10(full/NLC)'
################################################################################

set multiplot
set label "ratio log10(full/NLC)" font ",15" at graph 0.04, graph 1.05
set xrange [-2.0000e+00:2.0000e+00]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [1.2572e-09:1.8862e+02]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 13 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 13 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio log10(NLC/LC) wide'
################################################################################

set multiplot
set label "ratio log10(NLC/LC) wide" font ",15" at graph 0.04, graph 1.05
set xrange [-6.0000e+00:6.0000e+00]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [1.4222e-07:1.7224e+02]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 14 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 14 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio log10(full/LC) wide'
################################################################################

set multiplot
set label "ratio log10(full/LC) wide" font ",15" at graph 0.04, graph 1.05
set xrange [-6.0000e+00:6.0000e+00]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [4.1897e-08:2.3242e+02]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 15 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 15 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################

################################################################################
### Rendering of the plot titled 'ratio log10(full/NLC) wide'
################################################################################

set multiplot
set label "ratio log10(full/NLC) wide" font ",15" at graph 0.04, graph 1.05
set xrange [-6.0000e+00:6.0000e+00]
set bmargin 0 
set tmargin 0
set xtics nomirror
set ytics nomirror
set mytics 10
set xtics auto
set key horizontal noreverse maxcols 1 width -4 

#-- rendering subhistograms 'single diagram output'

set format y '10^{%T}'
set yrange [6.4103e-07:2.7858e+02]
set origin 0.0000e+00, 5.0000e-01
set size 1.0000e+00, 4.0000e-01
set mytics 10
set ytics auto
set format x ''
set logscale y
set ylabel "{/Symbol s} per bin [pb]"

plot \
'sum_2qq_6__.HwU' index 16 using (($1+$2)/2):($3 >= 0 ? sqrt(-1) : abs($3)) ls 101 title '',\
'sum_2qq_6__.HwU' index 16 using (($1+$2)/2):($3 < 0 ? sqrt(-1) : $3) ls 1 title '#1'
#-- rendering subhistograms 'Relative scale and PDF uncertainty'
unset label
unset format
set yrange [-1.4800e+00:1.4000e+00]
set origin 0.0000e+00, 3.5000e-01
set size 1.0000e+00, 1.5000e-01
set mytics 2
set ytics auto
set format x
unset logscale y
set ylabel "#1 rel.unc."
set label "Relative uncertainties w.r.t. central value" font ",15" front at graph 0.03, graph 0.13
plot \
0.0 ls 999 title ''

unset label

################################################################################
unset multiplot
!ps2pdf "sum_2qq_6__.ps" &> /dev/null