from __future__ import annotations

from importlib import metadata

from .logging import (
    DEFAULT_LOG_FORMAT,
    LOGGER_NAME,
    configure_logging,
    disable_logging,
    get_logger,
    progress,
)
from .color_plan import (
    ColorAccuracy,
    ColorSectorKind,
    GenericColorPlan,
    LCColorSector,
    LCQuarkLine,
    build_color_plan,
)
from .current_plan import (
    GenericAmplitudeStage,
    GenericColorSectorUseSummary,
    GenericClosureNode,
    GenericCurrentNode,
    GenericCurrentPlan,
    GenericCurrentStage,
    GenericInteractionNode,
    GenericStagePlan,
    build_generic_current_plan,
    build_generic_stage_plan,
)
from .generic_artifact import (
    GENERIC_DAG_PROCESS_ARTIFACT_KIND,
    GENERIC_DAG_PROCESS_SET_ARTIFACT_KIND,
    GENERIC_PROCESS_MANIFEST_KIND,
    GENERIC_PROCESS_SET_MANIFEST_KIND,
    GENERIC_PROCESS_SCHEMA_VERSION,
    GenericProcessManifest,
    GenericProcessSetManifest,
    build_generic_process_manifest,
    build_generic_process_set_manifest,
    load_generic_process_manifest,
    load_generic_process_set_manifest,
    write_generic_dag_process_artifact,
    write_generic_dag_process_set_artifact,
    write_generic_process_manifest,
    write_generic_process_set_manifest,
)
from .generic_dag import (
    AmplitudeRoot,
    ColorEngine,
    ColorFlow,
    ColorState,
    CurrentIndex as GenericCurrentIndex,
    CurrentNode as GenericDAGCurrentNode,
    GenericDAG,
    GenericDAGCompiler,
    InteractionNode as GenericDAGInteractionNode,
    QuantumFlow,
    compile_generic_dag,
)
from .lowering import (
    ColorAlgebraProbe,
    RecursionLoweringPlan,
    SymbolicLoweringReport,
    TensorNetworkProbe,
    TensorNetworkBlueprint,
    VertexLoweringReport,
    VertexLoweringStep,
    build_symbolic_lowering_report,
)
from .matrix import (
    GenerationResult,
    MatrixElementGenerator,
    MatrixGenerationBackend,
)
from .model import (
    AmplicolSMLeadingColorModel,
    Model,
    Particle,
    Vertex,
    VertexLoweringCoverageEntry,
    VertexLoweringCoverageReport,
    VertexLoweringRule,
)
from .params import (
    ParamBuilder,
    ParameterRange,
    SymbolicaEvaluatorBundle,
)
from .process_runtime import (
    ProcessArtifactManifest,
    ProcessRuntimeBackend,
    PythonProcessRuntime,
    load_process,
    load_process_manifest,
)
from .process_ir import (
    CanonicalProcessIR,
    ProcessLegIR,
    ProcessSetEntryIR,
    ProcessSetIR,
    QuarkLineSummary,
    build_process_ir,
    build_process_set_ir,
)
from .process_support import (
    ColorPlanSupportSummary,
    CurrentPlanSupportSummary,
    ProcessContent,
    ProcessSupportReport,
    classify_process_support,
    describe_process_content,
)
from .processes import (
    ParsedProcess,
    PhaseSpaceGroup,
    ProcessEnumeration,
    ProcessEnumerator,
    ProcessOptions,
    ProcessSelectionRecord,
    ProcessSelectionReport,
    ProcessSetEntry,
    ProcessSetEnumeration,
    SubprocessRecord,
    build_generic_process_selection_report,
    canonical_process_key,
    enumerate_processes,
    enumerate_process_set,
    expand_process_variants,
    split_process_set,
    write_legacy_process_file,
)
from .reference import (
    AmplicolAdapter,
    AmplicolFirstPoint,
    AmplicolWorkflowResult,
    CommandResult,
    TimingRow,
    parse_first_phase_space_point,
    parse_first_matrix_element,
    parse_timing_rows,
    popen_runner,
)
def _package_version() -> str:
    try:
        return metadata.version("pyamplicol")
    except metadata.PackageNotFoundError:
        return "0.0.1"


__version__ = _package_version()

__all__ = [
    "AmplicolAdapter",
    "AmplicolFirstPoint",
    "AmplicolSMLeadingColorModel",
    "AmplicolWorkflowResult",
    "AmplitudeRoot",
    "CanonicalProcessIR",
    "ColorAccuracy",
    "ColorEngine",
    "ColorFlow",
    "ColorSectorKind",
    "ColorState",
    "CommandResult",
    "ColorAlgebraProbe",
    "ColorPlanSupportSummary",
    "CurrentPlanSupportSummary",
    "DEFAULT_LOG_FORMAT",
    "GenerationResult",
    "GENERIC_DAG_PROCESS_ARTIFACT_KIND",
    "GENERIC_DAG_PROCESS_SET_ARTIFACT_KIND",
    "GENERIC_PROCESS_MANIFEST_KIND",
    "GENERIC_PROCESS_SET_MANIFEST_KIND",
    "GENERIC_PROCESS_SCHEMA_VERSION",
    "GenericAmplitudeStage",
    "GenericColorPlan",
    "GenericColorSectorUseSummary",
    "GenericClosureNode",
    "GenericCurrentIndex",
    "GenericCurrentNode",
    "GenericDAG",
    "GenericDAGCompiler",
    "GenericDAGCurrentNode",
    "GenericDAGInteractionNode",
    "GenericCurrentPlan",
    "GenericCurrentStage",
    "GenericInteractionNode",
    "GenericProcessManifest",
    "GenericProcessSetManifest",
    "GenericStagePlan",
    "LCColorSector",
    "LCQuarkLine",
    "LOGGER_NAME",
    "MatrixElementGenerator",
    "MatrixGenerationBackend",
    "Model",
    "ParamBuilder",
    "ParsedProcess",
    "ParameterRange",
    "Particle",
    "PhaseSpaceGroup",
    "ProcessArtifactManifest",
    "ProcessContent",
    "ProcessEnumeration",
    "ProcessEnumerator",
    "ProcessLegIR",
    "ProcessOptions",
    "ProcessSelectionRecord",
    "ProcessSelectionReport",
    "ProcessSetEntry",
    "ProcessSetEntryIR",
    "ProcessSetEnumeration",
    "ProcessSetIR",
    "ProcessRuntimeBackend",
    "PythonProcessRuntime",
    "ProcessSupportReport",
    "QuarkLineSummary",
    "QuantumFlow",
    "RecursionLoweringPlan",
    "SubprocessRecord",
    "build_generic_process_selection_report",
    "SymbolicaEvaluatorBundle",
    "SymbolicLoweringReport",
    "TensorNetworkBlueprint",
    "TensorNetworkProbe",
    "TimingRow",
    "Vertex",
    "VertexLoweringCoverageEntry",
    "VertexLoweringCoverageReport",
    "VertexLoweringReport",
    "VertexLoweringRule",
    "VertexLoweringStep",
    "__version__",
    "build_color_plan",
    "compile_generic_dag",
    "build_generic_current_plan",
    "build_generic_process_manifest",
    "build_generic_process_set_manifest",
    "build_generic_stage_plan",
    "canonical_process_key",
    "classify_process_support",
    "configure_logging",
    "build_symbolic_lowering_report",
    "build_process_ir",
    "build_process_set_ir",
    "disable_logging",
    "describe_process_content",
    "enumerate_processes",
    "enumerate_process_set",
    "expand_process_variants",
    "get_logger",
    "load_generic_process_manifest",
    "load_generic_process_set_manifest",
    "load_process",
    "load_process_manifest",
    "parse_first_phase_space_point",
    "parse_first_matrix_element",
    "parse_timing_rows",
    "popen_runner",
    "progress",
    "split_process_set",
    "write_legacy_process_file",
    "write_generic_dag_process_artifact",
    "write_generic_dag_process_set_artifact",
    "write_generic_process_manifest",
    "write_generic_process_set_manifest",
]
